# Generated by Django 5.0.7 on 2024-08-02 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_data_venda'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='VendaDeProduto',
        ),
    ]
