# Generated by Django 5.0.7 on 2024-08-02 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_produto_vendadeproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.novacategoria')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.novovalor')),
            ],
        ),
        migrations.CreateModel(
            name='VendaDoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField(blank=True, null=True)),
                ('data_venda', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
        ),
        migrations.DeleteModel(
            name='VendaDeProduto',
        ),
    ]
