# Generated by Django 5.0.7 on 2024-08-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_produto_vendadoproduto_delete_vendadeproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendadoproduto',
            name='data_venda',
            field=models.DateField(),
        ),
    ]
